services:
    Siganushka\GenericBundle\Doctrine\EventListener\SortableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Siganushka\GenericBundle\Doctrine\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
